import course

COURSES = [
    course.Course(period=1,
                  name='Intro to Computer Science',
                  teacher_name='Ms. Lee',
                  resource_name='repl.it',
                  resource_url='https://repl.it/'),
    course.Course(period=2,
                  name='Italian 2',
                  teacher_name='Ms. Franceschi',
                  resource_name='Word Ref.',
                  resource_url='http://www.wordreference.com/'),
    course.Course(period=3,
                  name='Algebra 2',
                  teacher_name='Mr. Shelton',
                  resource_name='Khan Academy',
                  resource_url='https://www.khanacademy.org/math/algebra2'),
    course.Course(period=4,
                  name='Government',
                  teacher_name='Mr. Capitan',
                  resource_name='Amendments',
                  resource_url='hrlibrary.umn.edu/education/all_amendments_usconst.htm'),
    course.Course(period=5,
                  name='ERWC',
                  teacher_name='Ms. Dano',
                  resource_name='Audio Book',
                  resource_url='https://www.audiobooks.com/'),
    course.Course(period=6,
                  name='Biotech 1/2',
                  teacher_name='Mr. Ng',
                  resource_name='Wikipedia',
                  resource_url='https://en.wikipedia.org/wiki/Biology'),
]
